### ISSUE TITLE
missing header file ?

### ISSUE THREAD

**Issue by vslavav** [edgeyoda/esp32_temperature#1]
Hi, 
can't find the following header file: esp32_temperature_inference.h
Please help

**Comment by edgeyoda** [comment]
Hi, that is generated automatically when you export to Arduino project from the Edge Impulse studio's "Deployment tab" and will be included when you add the Arduino.zip to your Arduino project.

**Comment by vslavav** [comment]
Thanks for a quick response. I did generate Arduino project. There is no esp32_temperature_inference.h there. Instead I see file ei_temperature_sensor_inference.h. Is this a same file ?

**Comment by edgeyoda** [comment]
ahhh yes, sorry for the inconvenience, I had changed the name of the Edge Impulse Project to ei_temperature_sensor to make it more generic and didn't update the .ino file in this repo yet. So yes it is the same file.

**Comment by vslavav** [comment]
Great. I'm using Arduino 1.8.13. I selected the following board: ESP32 Dev Module. When trying to compile, I got the following error: fork/exec C:\Users\Slava\AppData\Local\Arduino15\packages\esp32\tools\xtensa-esp32-elf-gcc\1.22.0-80-g6c4433a-5.2.0/bin/xtensa-esp32-elf-gcc.exe: The filename or extension is too long.

You probably was able to compile with no error.
Please help

**Comment by edgeyoda** [comment]
This was a common issue experienced with this but should be fixed in the next major release of Arduino IDE. Try installing the latest hourly build since I believe the fix is in there already. Alternatively, another workaround is also discussed in post 34 of 64 here: https://forum.edgeimpulse.com/t/esp32-cam-support/797/34 which requires you to drop in the platform.local file that is mentioned there.
